learning_users_dep/basic_app/urls.py
from django.urls import path

from . import views
app_name = 'basic_app'
urlpatterns = [
    path('register/', views.register, name='register'),
]

learning_users_dep/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views as basic_views


urlpatterns = [
    path('', basic_views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic/', include('basic_app.urls')),
    path('login/', basic_views.user_login, name='login'),
    path('logout/', basic_views.user_logout, name='logout'),
    path('special/', basic_views.special, name='special'),
]

learning_users_dep/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
    )

    #additional
    portfolio_link = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

learning_users_dep/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')
        
        
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = models.UserProfileInfo
        fields = ('portfolio_link','profile_pic')
    

learning_users_dep/basic_app/views.py
from django.shortcuts import render


from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from . import forms
# Create your views here.

def index(request):
    return render(request, 'index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in, nice!")


def register(request):
    registered = False

    if request.method == "POST":
        user_form = forms.UserForm(data=request.POST)
        profile_form = forms.UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                 profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = forms.UserForm()
        profile_form = forms.UserProfileInfoForm()

    return render(request, 'registration.html', {'user_form': user_form,
                                                 'profile_form': profile_form,
                                                 'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active')
        else:
            print("someone tried to login and failed!")
            print("Username: {} and password {}".format(username, password))
            return HttpResponse('Invalid login details supplied!')
    else:
        return render(request, 'login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

learning_users_dep/templates/base.html
<!DOCTYPE html>

<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
        {% block styling %}{% endblock %}
    </head>

    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'admin:index' %}">Admin<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'basic_app:register' %}">Register</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                        </li>
                        <li class="nav_item">
                            <a class="nav-link" href="{% url 'special' %}">Special</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Login</a>
                        </li>
                        {% endif %}
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        <li><a class="nav-link" href="{% url 'special' %}">{{ user.username }}</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            {% block content %}{% endblock %}
        </div>

    </body>
</html>

learning_users_dep/templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title %}INDEX PAGE{% endblock %}

{% block styling %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
    <div class="jumbotron">
        <h1>Welcome to the index page</h1>
    </div>
{% endblock %}

learning_users_dep/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <h1>Please log in</h1>
    <form action="{% url 'login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" name="" value="Login">

    </form>
{% endblock %}

learning_users_dep/templates/registration.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title %}Registration page{% endblock %}

{% block content %}
    <div>
        {% if registered %}
            <h1>Thank you for registering!</h1>
        {% else %}
            <h1>Register here</h1>
            <h3>Fill out the form</h3>

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" class="btn btn-outline-success" value="Register">
            </form>
        {% endif %}
    </div>
{% endblock %}